const RECEIPT_STATUS = {
  ACTIVE: 'ACTIVE',
  FULLY_ALLOCATED: 'FULLY_ALLOCATED',
  CANCELLED: 'CANCELLED',
};

const SALE_PAYMENT_STATUS_MAP = {
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
};

const DEFAULT_SEARCH_LIMIT = 20;
const MAX_SEARCH_LIMIT = 200;
const DEFAULT_CANDIDATE_LIMIT = 50;
const MAX_CANDIDATE_LIMIT = 200;

const PAYMENT_METHOD_VALUES = new Set([
  'CASH',
  'TRANSFER',
  'CARD',
  'QR',
  'E_WALLET',
  'CHEQUE',
  'OTHER',
  'DEPOSIT',
]);

const PAYMENT_METHOD_ALIASES = {
  QR_CODE: 'QR',
  QR_PAYMENT: 'QR',
  BANK_TRANSFER: 'TRANSFER',
  CREDIT_CARD: 'CARD',
  EWALLET: 'E_WALLET',
  E_WALLET_PAYMENT: 'E_WALLET',
};

module.exports = {
  RECEIPT_STATUS,
  SALE_PAYMENT_STATUS_MAP,
  DEFAULT_SEARCH_LIMIT,
  MAX_SEARCH_LIMIT,
  DEFAULT_CANDIDATE_LIMIT,
  MAX_CANDIDATE_LIMIT,
  PAYMENT_METHOD_VALUES,
  PAYMENT_METHOD_ALIASES,
};
