'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..', '..', '..');
const schema = fs.readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8');
const sql = fs.readFileSync(path.join(__dirname, 'migration.sql'), 'utf8');
const brand = schema.match(/model Brand \{([\s\S]*?)\n\}/)?.[1];
assert.ok(brand, 'Brand model must exist');
assert.match(schema, /model Branch \{[\s\S]*?\n\s+brands\s+Brand\[\]/);
assert.match(brand, /\n\s+branchId\s+Int\?/);
assert.match(brand, /branch\s+Branch\?\s+@relation\(fields: \[branchId\], references: \[id\]\)/);
assert.doesNotMatch(brand, /branch\s+Branch\?\s+@relation\([^\n]*(?:onDelete|onUpdate)/);
assert.match(brand, /normalizedName\s+String\s+@unique/);
assert.doesNotMatch(brand, /@@unique\(\[branchId, normalizedName\]\)/);
for (const index of ['@@index([branchId])','@@index([branchId, active])','@@index([branchId, normalizedName])']) assert.ok(brand.includes(index));
assert.match(sql, /ON DELETE SET NULL ON UPDATE CASCADE/);
assert.ok(!/\b(?:UPDATE\s+"Brand"|DELETE\s+FROM|INSERT\s+INTO|MERGE|DROP|TRUNCATE)\b/i.test(sql));
console.log('Brand tenant ownership additive Prisma migration contract: PASS');
