const express = require('express')
const router = express.Router()

const productCatalogController = require('../catalog/controllers/productCatalogController')
const productCreateLegacyCompatibilityController = require('../create/controllers/productCreateLegacyCompatibilityController')
const productCreateDropdownCompatibilityController = require('../create/controllers/productCreateDropdownCompatibilityController')
const productCreatePosCompatibilityController = require('../create/controllers/productCreatePosCompatibilityController')
const productRuntimeLookupController = require('../runtimeLookup/controllers/productRuntimeLookupController')
const productPosQueryController = require('../posQuery/controllers/productPosQueryController')
const productOnlineQueryController = require('../onlineQuery/controllers/productOnlineQueryController')
const productTemplateCloneController = require('../templateClone/controllers/productTemplateCloneController')
const readyToSellController = require('../readyToSell/controllers/readyToSellController')
const productDuplicatePreviewRoutes = require('../duplicatePreview/routes/productDuplicatePreviewRoutes')
const productMaintenanceController = require('../maintenance/controllers/productMaintenanceController')
const productPricingController = require('../pricing/controllers/productPricingController')
const productMediaController = require('../media/controllers/productMediaController')
const productLifecycleController = require('../lifecycle/controllers/productLifecycleController')
const productStockModeMigrationController = require('../stockModeMigration/controllers/productStockModeMigrationController')
const verifyToken = require('../../../../middlewares/verifyToken')

router.get('/online/dropdowns', productCreateDropdownCompatibilityController.getProductDropdowns)
router.get('/online/search', productOnlineQueryController.searchProducts)
router.get('/online/detail/:id', productOnlineQueryController.getProductById)

router.use(verifyToken)

router.get('/dropdowns', productCreateDropdownCompatibilityController.getProductDropdowns)
router.use('/duplicate-preview', productDuplicatePreviewRoutes)
router.get('/pos/search', productPosQueryController.searchProducts)
router.get('/pos/runtime-by-template/:templateProductId', productRuntimeLookupController.getOperationalProductByTemplateId)
router.post('/pos/create-local', productCreatePosCompatibilityController.createLocalOperationalProduct)
router.post('/pos/create-from-template', productTemplateCloneController.createOperationalProductFromTemplate)
router.get('/pos/:id', productPosQueryController.getProductById)

router.get('/ready-to-sell', readyToSellController.getReadyToSellProducts)
router.get('/ready-to-sell/structured/:productId', readyToSellController.getStructuredReadyToSellDetails)

router.get('/', productCatalogController.getAllProducts)
router.post('/', productCreateLegacyCompatibilityController.createProduct)
router.patch('/:id', productMaintenanceController.updateProduct)
router.post('/:id/disable', productLifecycleController.disableProduct)
router.post('/:id/enable', productLifecycleController.enableProduct)
router.get('/:id/delete-check', productLifecycleController.getProductDeleteCheck)
router.patch('/:id/archive', productLifecycleController.archiveProduct)
router.get('/:id', productPosQueryController.getProductById)
router['delete']('/:id', productLifecycleController.deleteProduct)
router['delete']('/:id/images', productMediaController.deleteProductImage)
router.post('/:id/migrate-to-simple', productStockModeMigrationController.migrateSnToSimple)

router.get('/:productId/prices', productPricingController.getProductPrices)
router.put('/:productId/prices', productPricingController.updateProductPrices)
router.post('/:productId/prices', productPricingController.addProductPrice)
router['delete']('/:productId/prices/:priceId', productPricingController.deleteProductPrice)

module.exports = router
