const SaleReturnFailureCode = Object.freeze({
  ACTOR_REQUIRED: 'RETURN_ACTOR_REQUIRED',
  INVALID_COMMAND_ID: 'INVALID_COMMAND_ID',
  INVALID_SALE_ID: 'INVALID_SALE_ID',
  ITEMS_REQUIRED: 'RETURN_ITEMS_REQUIRED',
  INVALID_ITEM: 'INVALID_RETURN_ITEM',
  INVALID_AMOUNT: 'INVALID_RETURN_AMOUNT',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  COMMAND_MISMATCH: 'RETURN_COMMAND_MISMATCH',
  COMPLETION_CONFLICT: 'RETURN_COMPLETION_CONFLICT',
  STOCK_CONFLICT: 'RETURN_STOCK_CONFLICT',
  QUANTITY_CONFLICT: 'RETURN_QUANTITY_CONFLICT',
  REFUND_EXCEEDS_ELIGIBLE: 'REFUND_EXCEEDS_ELIGIBLE',
  REFUND_EVIDENCE_MISMATCH: 'REFUND_EVIDENCE_MISMATCH',
  DEDUCTION_REASON_REQUIRED: 'DEDUCTION_REASON_REQUIRED',
  DEDUCTION_APPROVAL_REQUIRED: 'DEDUCTED_REFUND_APPROVAL_REQUIRED',
  INVALID_SOURCE_PAYMENT: 'INVALID_SOURCE_PAYMENT',
});

module.exports = { SaleReturnFailureCode };
