const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const schema = read('prisma/partner-store-application.prisma')
const routes = read('src/modules/partnerStore/application/partnerStoreApplicationRoutes.js')
const facade = read('src/modules/partnerStore/application/partnerStoreProvisioningService.js')
const runtime = read('src/modules/partnerStore/application/partnerStoreProvisioningTransactionalService.js')

assert.ok(schema.includes('enum PartnerStoreProvisioningStatus'))
assert.ok(schema.includes('PROVISIONING_STARTED'))
assert.ok(schema.includes('STORE_PROVISIONED'))
assert.ok(schema.includes('PROVISIONING_FAILED'))
assert.ok(schema.includes('provisioningStatus'))
assert.ok(routes.includes("post('/:id/provision'"))
assert.ok(!routes.includes("post('/:id/activate'"))
assert.ok(facade.includes("require('./partnerStoreProvisioningTransactionalService')"))
assert.ok(runtime.includes("application.status !== 'APPROVED'"))
assert.ok(runtime.includes("provisioningStatus === 'PROVISIONED'"))
assert.ok(runtime.includes("provisioningStatus === 'IN_PROGRESS'"))
assert.ok(runtime.includes('repository.withTransaction'))
assert.ok(runtime.includes('tx.branch.create'))
assert.ok(runtime.includes('tx.partnerStoreCapability.create'))
assert.ok(runtime.includes('reconcileLegacyProvisionedState'))
assert.ok(runtime.includes("where: { id: application.provisionedBranchId }"))
assert.ok(runtime.includes("PARTNER_STORE_PROVISIONED_BRANCH_MISSING"))
assert.ok(runtime.includes("where: { branchId: branch.id }"))
assert.ok(runtime.includes("provisioningStatus: { in: ['NOT_STARTED', 'FAILED', 'IN_PROGRESS'] }"))
assert.ok(runtime.includes('reconciledLegacyState: true'))
assert.ok(runtime.includes('capabilityCreated: !existingCapability'))
assert.ok(runtime.includes("if (reconciled) return reconciled"))
assert.ok(!runtime.includes('STALE_AFTER_MS'))
assert.ok(!runtime.includes('tx.user.create'))
assert.ok(!runtime.includes('tx.employeeProfile.create'))
assert.ok(!runtime.includes('enabled: true'))

console.log('partner store provisioning v2 contract: PASS')
