const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const schema = read('prisma/partner-store-application.prisma')
const migration = read('prisma/migrations/20260814025000_partner_store_activation_v2/migration.sql')
const service = read('src/modules/partnerStore/application/partnerStoreActivationService.js')
const routes = read('src/modules/partnerStore/application/partnerStoreApplicationRoutes.js')
const publicRoutes = read('src/modules/partnerStore/application/partnerStoreActivationPublicRoutes.js')
const provisioning = read('src/modules/partnerStore/application/partnerStoreProvisioningTransactionalService.js')

assert.ok(schema.includes('enum PartnerStoreActivationStatus'))
assert.ok(schema.includes('NOT_STARTED'))
assert.ok(schema.includes('INVITED'))
assert.ok(schema.includes('ACTIVE'))
assert.ok(schema.includes('model PartnerStoreActivationInvitation'))
assert.ok(schema.includes('revokedAt'))
assert.ok(schema.includes('consumedAt'))
assert.ok(schema.includes('previousActivationStatus'))
assert.ok(schema.includes('resultingActivationStatus'))

assert.ok(migration.includes('CREATE TABLE "PartnerStoreActivationInvitation"'))
assert.ok(migration.includes('ADD COLUMN "activationStatus"'))
assert.ok(migration.includes('ADD COLUMN "revokedAt"'))
assert.ok(!migration.includes('DROP TABLE'))
assert.ok(!migration.includes('DROP COLUMN'))

assert.ok(service.includes("crypto.createHash('sha256')"))
assert.ok(service.includes('crypto.randomBytes(32)'))
assert.ok(service.includes('expiresAt'))
assert.ok(service.includes('revokedAt'))
assert.ok(service.includes('consumedAt'))
assert.ok(service.includes("activationStatus: 'ACTIVE'"))
assert.ok(service.includes("v2Role: 'OWNER'"))
assert.ok(service.includes("role: 'ADMIN'"))
assert.ok(service.includes('findIdentityConflict'))
assert.ok(service.indexOf('assertUsableInvitation(invitation)') < service.indexOf('bcrypt.hash(password, 10)'))
assert.ok(service.includes("eventType: 'ACTIVATION_INVITATION_ISSUED'"))
assert.ok(service.includes("eventType: 'OWNER_ACTIVATED'"))

assert.ok(routes.includes("post('/:id/activation-invitations'"))
assert.ok(routes.includes("publicRouter.use('/activation', activationPublicRoutes)"))
assert.ok(publicRoutes.includes("router.post('/claim', controller.claim)"))

assert.ok(!provisioning.includes('employeeProfile.create'))
assert.ok(!provisioning.includes('user.create'))
assert.ok(!provisioning.includes("activationStatus: 'ACTIVE'"))

console.log('partner store activation v2 contract: PASS')
