const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const schema = read('prisma/partner-store-application.prisma')
const migration = read('prisma/migrations/20260814043000_partner_store_first_login_onboarding_v2/migration.sql')
const service = read('src/modules/partnerStore/onboarding/partnerStoreOnboardingService.js')
const routes = read('src/modules/partnerStore/onboarding/partnerStoreOnboardingRoutes.js')
const partnerRoutes = read('src/modules/partnerStore/routes/partnerStoreCapabilityRoutes.js')
const activation = read('src/modules/partnerStore/application/partnerStoreActivationService.js')

assert.ok(schema.includes('enum PartnerStoreOnboardingStatus'))
assert.ok(schema.includes('OWNER_FIRST_LOGIN'))
assert.ok(schema.includes('ONBOARDING_STARTED'))
assert.ok(schema.includes('ONBOARDING_COMPLETED'))
assert.ok(schema.includes('firstLoginAt'))
assert.ok(schema.includes('onboardingStartedAt'))
assert.ok(schema.includes('onboardingCompletedAt'))
assert.ok(schema.includes('previousOnboardingStatus'))
assert.ok(schema.includes('resultingOnboardingStatus'))

assert.ok(migration.includes('CREATE TYPE "PartnerStoreOnboardingStatus"'))
assert.ok(migration.includes('ADD COLUMN "onboardingStatus"'))
assert.ok(migration.includes('ADD COLUMN "firstLoginAt"'))
assert.ok(!migration.includes('DROP TABLE'))
assert.ok(!migration.includes('DROP COLUMN'))

assert.ok(service.includes('findUnique'))
assert.ok(service.includes('provisionedOwnerUserId'))
assert.ok(service.includes("activationStatus !== 'ACTIVE'"))
assert.ok(service.includes("eventType: 'OWNER_FIRST_LOGIN'"))
assert.ok(service.includes("eventType: 'ONBOARDING_STARTED'"))
assert.ok(service.includes("eventType: 'ONBOARDING_COMPLETED'"))
assert.ok(service.includes('payload.confirmStoreProfile !== true'))
assert.ok(service.includes('payload.confirmOwnerContact !== true'))
assert.ok(service.includes("onboardingStatus: 'COMPLETED'"))
assert.ok(service.includes('isPartnerStoreOwner: false'))
assert.ok(service.includes('updateMany'))
assert.ok(service.includes('firstLoginClaim.count === 1'))
assert.ok(service.includes('startClaim.count === 1'))
assert.ok(service.includes('completionClaim.count === 1'))

assert.ok(routes.includes("router.get('/me'"))
assert.ok(routes.includes("router.post('/complete'"))
assert.ok(routes.includes('verifyToken'))
assert.ok(partnerRoutes.includes("router.use('/onboarding', onboardingRoutes)"))

assert.ok(!activation.includes('onboardingStatus'))
assert.ok(!activation.includes('ONBOARDING_COMPLETED'))

console.log('partner store first login onboarding v2 contract: PASS')
