const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const schema = read('prisma/partner-store-application.prisma')
const migration = read('prisma/migrations/20260814051500_partner_store_operational_readiness_v2/migration.sql')
const service = read('src/modules/partnerStore/readiness/partnerStoreOperationalReadinessService.js')
const routes = read('src/modules/partnerStore/readiness/partnerStoreOperationalReadinessRoutes.js')
const partnerRoutes = read('src/modules/partnerStore/routes/partnerStoreCapabilityRoutes.js')
const onboarding = read('src/modules/partnerStore/onboarding/partnerStoreOnboardingService.js')
const platformVerification = read('src/modules/system/operational-verification/operationalVerificationService.js')

assert.ok(schema.includes('enum PartnerStoreOperationalReadinessStatus'))
assert.ok(schema.includes('NOT_READY'))
assert.ok(schema.includes('CERTIFIED'))
assert.ok(schema.includes('OPERATIONAL_CERTIFIED'))
assert.ok(schema.includes('operationalCertifiedAt'))
assert.ok(schema.includes('operationalCertifiedByUserId'))
assert.ok(schema.includes('operationalCertificationSnapshot'))
assert.ok(schema.includes('previousOperationalReadinessStatus'))
assert.ok(schema.includes('resultingOperationalReadinessStatus'))

assert.ok(migration.includes('CREATE TYPE "PartnerStoreOperationalReadinessStatus"'))
assert.ok(migration.includes('ADD COLUMN "operationalReadinessStatus"'))
assert.ok(migration.includes('ADD COLUMN "operationalCertificationSnapshot"'))
assert.ok(!migration.includes('DROP TABLE'))
assert.ok(!migration.includes('DROP COLUMN'))

assert.ok(service.includes("'lifecycle'"))
assert.ok(service.includes("'branchIdentity'"))
assert.ok(service.includes("'ownerContact'"))
assert.ok(service.includes("'capability'"))
assert.ok(service.includes("'serviceMode'"))
assert.ok(service.includes("application?.onboardingStatus === 'COMPLETED'"))
assert.ok(service.includes('partnerStoreCapability.findUnique'))
assert.ok(service.includes('pickupEnabled || capability?.deliveryEnabled'))
assert.ok(service.includes("operationalReadinessStatus: 'CERTIFIED'"))
assert.ok(service.includes("eventType: 'OPERATIONAL_CERTIFIED'"))
assert.ok(service.includes('operationalCertificationSnapshot: snapshot'))
assert.ok(service.includes("operationalReadinessStatus: 'NOT_READY'"))
assert.ok(service.includes('claimed.count === 1'))

assert.ok(routes.includes("router.get('/me'"))
assert.ok(routes.includes("router.post('/certify'"))
assert.ok(routes.includes('verifyToken'))
assert.ok(partnerRoutes.includes("router.use('/readiness', operationalReadinessRoutes)"))

assert.ok(!onboarding.includes('OPERATIONAL_CERTIFIED'))
assert.ok(!platformVerification.includes('PartnerStoreOperationalReadinessStatus'))

console.log('partner store operational readiness v2 contract: PASS')
