const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const routes = read('src/modules/productTemplate/candidates/routes/productTemplateCandidateRoutes.js')
const service = read('src/modules/productTemplate/candidates/quality/resolveCatalogDuplicateCandidateService.js')
const repository = read('src/modules/productTemplate/candidates/quality/resolveCatalogDuplicateCandidateRepository.js')
const schema = read('prisma/platform/product-template.prisma')

assert.match(routes, /router\.post\('\/:id\/resolve-duplicate'/)
assert.match(service, /canonicalTemplateProductId/)
assert.match(service, /duplicateTemplateProductId/)
assert.match(service, /CANDIDATE_DUPLICATE_RESOLUTION_INVALID/)
assert.match(repository, /prisma\.\$transaction/)
assert.match(repository, /pg_advisory_xact_lock/)
assert.match(repository, /templateProductId:\s*Number\(duplicateTemplateProductId\)/)
assert.match(repository, /templateProductId:\s*Number\(canonicalTemplateProductId\)/)
assert.match(repository, /active:\s*false/)
assert.match(repository, /status:\s*'RESOLVED'/)
assert.match(repository, /eventType:\s*'DUPLICATE_RESOLVED'/)
assert.match(repository, /remainingReferenceCount/)
assert.match(schema, /DUPLICATE_RESOLVED/)
assert.ok(!repository.includes('saleItem'))
assert.ok(!repository.includes('stockMovement'))
assert.ok(!repository.includes('purchaseOrderItem'))

console.log('product-template-catalog-quality-duplicate-resolution.contract.test.js: PASS')
