const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')
const routes = read('src/modules/productTemplate/candidates/routes/productTemplateCandidateRoutes.js')
const service = read('src/modules/productTemplate/candidates/quality/createCatalogQualityCandidateService.js')
const repository = read('src/modules/productTemplate/candidates/quality/createCatalogQualityCandidateRepository.js')

assert.match(routes, /router\.post\('\/quality', createCatalogQualityCandidate\)/)
for (const type of ['POSSIBLE_DUPLICATE', 'QUALITY_REVIEW', 'ORPHAN_UNUSED']) assert.ok(service.includes(type))
assert.match(service, /assertSuperAdmin\(user\)/)
assert.match(service, /TEMPLATE_BRANCH_INVALID/)
assert.match(service, /CANDIDATE_BUSINESS_TYPE_MISMATCH/)
assert.match(service, /DUPLICATE_COMPARISON_REQUIRED/)
assert.match(service, /buildCandidateDedupeKey/)
assert.match(repository, /productTemplateCandidate\.create/)
assert.match(repository, /status:\s*'OPEN'/)
assert.match(repository, /eventType:\s*'CREATED'/)
assert.match(repository, /templateBranchId/)
assert.match(repository, /primaryTemplateProductId/)
assert.match(repository, /comparisonTemplateProductId/)
assert.match(repository, /dedupeKey/)
console.log('product-template-catalog-quality-candidate-runtime-foundation.contract.test.js: PASS')
