const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const read = (file) => fs.readFileSync(path.resolve(__dirname, '..', file), 'utf8')
const create = read('src/modules/product/runtime/services/operationalProductRuntimeService.js')
const update = read('src/modules/product/maintenance/services/productMaintenanceService.js')
const repository = read('src/modules/product/runtime/repositories/operationalProductRuntimeRepository.js')
const catalog = read('src/modules/sales/catalog/controllers/saleCatalogSearchController.js')
const availability = read('src/modules/product/runtime/calculations/operationalStockAvailability.js')
assert.match(create, /inventoryBehavior,\s*saleBarcode,\s*noSN/)
assert.match(create, /SALE_BARCODE_REQUIRES_SIMPLE_MODE/)
assert.match(create, /SALE_BARCODE_ALREADY_EXISTS_IN_BRANCH/)
assert.match(update, /decideOperationalProductMode/)
assert.match(update, /saleBarcode: data\.saleBarcode !== undefined/)
assert.doesNotMatch(update, /const decideMode =/)
assert.match(repository, /inventoryBehavior: true/)
assert.match(repository, /saleBarcode: true/)
assert.match(repository, /findSimpleProductBySaleBarcode/)
assert.match(create, /const stockItem = await findStockItemByBarcode/)
assert.match(create, /findSimpleProductBySaleBarcode/)
assert.match(catalog, /product\.saleBarcode/)
assert.match(catalog, /orderBy: \{ receivedAt: 'asc' \}/)
assert.match(availability, /inventoryBehavior === 'NON_STOCK'/)
console.log('Product Inventory Runtime Contract: PASS')
