const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const routes = read('src/modules/productTemplate/candidates/routes/productTemplateCandidateRoutes.js')
const service = read('src/modules/productTemplate/candidates/quality/discoverCatalogDuplicateCandidatesService.js')
const repository = read('src/modules/productTemplate/candidates/quality/discoverCatalogDuplicateCandidatesRepository.js')
const assessment = read('src/modules/productTemplate/candidates/quality/catalogDuplicateAssessment.js')

assert.match(routes, /router\.post\('\/quality\/scan'/)
assert.match(service, /POSSIBLE_DUPLICATE/)
assert.match(service, /buildCandidateBuckets/)
assert.match(service, /scoreDuplicatePair/)
assert.match(service, /templateBranchId/)
assert.match(service, /businessType/)
assert.match(service, /apply/)
assert.match(service, /createCatalogQualityCandidate/)
assert.match(service, /assessmentEvidence/)
assert.match(service, /confidenceSummary/)
assert.match(assessment, /buildAssessedDuplicatePairs/)
assert.match(repository, /product\.findMany/)
assert.match(repository, /productType:\s*{[\s\S]*branchId:/)
assert.match(repository, /clonedProducts/)
assert.ok(!service.includes('sourceBranchId'))
assert.ok(!service.includes('sourceProductId'))
assert.ok(!service.includes('PROMOTED'))

console.log('product-template-catalog-quality-duplicate-discovery.contract.test.js: PASS')
