const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const routes = read('src/modules/productTemplate/candidates/routes/productTemplateCandidateRoutes.js')
const service = read('src/modules/productTemplate/candidates/quality/discoverCatalogOrphanCandidatesService.js')
const repository = read('src/modules/productTemplate/candidates/quality/discoverCatalogOrphanCandidatesRepository.js')
const archiveRepository = read('src/modules/productTemplate/candidates/quality/archiveCatalogOrphanCandidateRepository.js')

assert.match(routes, /router\.post\('\/quality\/scan-orphans'/)
assert.match(service, /ORPHAN_UNUSED/)
assert.match(service, /templateBranchId/)
assert.match(service, /businessType/)
assert.match(service, /apply/)
assert.match(service, /createCatalogQualityCandidate/)
assert.match(repository, /clonedProducts:\s*{\s*none:\s*{}\s*}/)
assert.match(repository, /productType:\s*{\s*branchId:/)
assert.match(archiveRepository, /pg_advisory_xact_lock/)
assert.match(archiveRepository, /clonedProducts/)
assert.match(archiveRepository, /templateProductId:\s*product\.id/)
assert.match(archiveRepository, /active:\s*false/)
assert.ok(!archiveRepository.includes('saleItem'))
assert.ok(!archiveRepository.includes('stockMovement'))
assert.ok(!archiveRepository.includes('purchaseOrderItem'))

console.log('product-template-catalog-quality-orphan-discovery.contract.test.js: PASS')
