const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (relativePath) => fs.readFileSync(path.resolve(__dirname, '..', relativePath), 'utf8')

const serviceSource = read('src/modules/product/templateClone/services/productTemplateCloneService.js')
const controllerSource = read('src/modules/product/templateClone/controllers/productTemplateCloneController.js')

assert.match(serviceSource, /normalizeProductTypeIdentity/)
assert.match(serviceSource, /assertProductTypeGlobalMappingIntegrity/)
assert.match(serviceSource, /PRODUCT_TYPE_GLOBAL_MAPPING_CONFLICT/)
assert.match(serviceSource, /GLOBAL_PRODUCT_TYPE_AUTHORITY_MISSING/)
assert.match(serviceSource, /GLOBAL_PRODUCT_TYPE_ID_MISMATCH/)
assert.doesNotMatch(serviceSource, /TEMPLATE_PRODUCT_TYPE_SEMANTIC_DRIFT/)
assert.doesNotMatch(serviceSource, /BRANCH_PRODUCT_TYPE_SEMANTIC_DRIFT/)

assert.match(serviceSource, /globalProductType:\s*\{[\s\S]*name:\s*true/)
assert.match(serviceSource, /const templateType = await db\.productType\.findFirst/)
assert.match(serviceSource, /const candidates = await db\.productType\.findMany/)
assert.match(serviceSource, /candidateIdentity === identity/)
assert.match(serviceSource, /assertProductTypeGlobalMappingIntegrity\(\{[\s\S]*branchType: existing/)
assert.match(serviceSource, /assertProductTypeGlobalMappingIntegrity\(\{[\s\S]*branchType: created/)
assert.match(serviceSource, /assertProductTypeGlobalMappingIntegrity\(\{[\s\S]*branchType: concurrent/)

const lockIndex = serviceSource.indexOf('await acquireForwardCloneLock({')
const traceLookupIndex = serviceSource.indexOf('const existing = await findOperationalRuntimeProductByTemplateId')
const globalTypeIndex = serviceSource.indexOf('const globalProductTypeId = template.productType?.globalProductTypeId')
const adoptionIndex = serviceSource.indexOf('const { branchType } = await adoptBranchProductType')
const createIndex = serviceSource.indexOf('const created = await createOperationalProductRecordFromTemplate')
assert.ok(lockIndex >= 0, 'forward clone lock must exist')
assert.ok(traceLookupIndex > lockIndex, 'exact-template trace lookup must run after serialization lock')
assert.ok(globalTypeIndex > traceLookupIndex, 'existing traced Local Product must resolve before Template taxonomy validation')
assert.ok(adoptionIndex > globalTypeIndex, 'ProductType adoption must run only for new materialization')
assert.ok(createIndex > adoptionIndex, 'ProductType integrity must run before new Product creation')

assert.match(controllerSource, /error\?\.details \? \{ details: error\.details \} : \{\}/)
assert.match(controllerSource, /status >= 400 && status < 500/)
assert.match(controllerSource, /req\.employee\?\.v2Role\s*\|\|[\s\S]*req\.employee\?\.role/)

console.log('Product Template Clone Type Integrity Contract: PASS')
