'use strict'
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8')
const service = read('src/modules/storeDevice/services/storeDeviceDurableJobService.js')
const policy = read('src/modules/storeDevice/policies/storeDeviceAuthorityPolicy.js')
const repository = read('src/modules/storeDevice/repositories/storeDeviceRepository.js')
const routes = read('src/modules/storeDevice/routes/storeDeviceRoutes.js')
for (const token of ['requireBranchAuthority', 'assertActiveGatewaySession', 'STORE_DEVICE_CROSS_BRANCH_ACCESS_DENIED', 'STORE_DEVICE_GATEWAY_SESSION_INACTIVE', 'STORE_DEVICE_JOB_TERMINAL', 'assertRetryable', 'STORE_DEVICE_JOB_NOT_RETRYABLE']) assert.ok(policy.includes(token), token)
for (const token of ['branchId_idempotencyKey', 'prisma.$transaction', 'createLeaseAtomically', 'createResultOnce', 'findLease', 'gatewayId, sessionId, status', 'status: { in: [\'OFFERED\', \'ACKNOWLEDGED\'] }']) assert.ok(repository.includes(token), token)
for (const token of ['registerGateway', 'authenticateSession', 'reconnectSession', 'heartbeat', 'disconnectSession', 'rotateGateway', 'revokeGateway', 'createJob', 'listJobs', 'leaseJob', 'acknowledgeOrProgress', 'complete', 'retry', 'diagnostics', 'STORE_DEVICE_LEASE_HELD', 'STORE_DEVICE_RETRY_IDEMPOTENCY_REQUIRED']) assert.ok(service.includes(token), token)
for (const token of ['/sessions/:sessionId/reconnect', '/sessions/:sessionId/heartbeat', '/sessions/:sessionId/disconnect', '/gateways/:gatewayId/revoke', '/jobs/:jobId/leases', '/leases/:leaseId/complete', '/leases/:leaseId/fail', '/jobs/:jobId/retry', '/diagnostics']) assert.ok(routes.includes(token), token)
assert.doesNotMatch(`${service}\n${repository}`, /(?:proofKey|privateKey|accessToken|refreshToken|certificate)\s*[:=]/i)
console.log('store device durable job API contract: PASS')
