CREATE TYPE "TaxExpenseStatus" AS ENUM ('DRAFT','RECORDED','UNDER_REVIEW','FINALIZED','VOIDED');
CREATE TYPE "TaxExpenseCounterpartyType" AS ENUM ('SUPPLIER','OTHER');
CREATE TYPE "TaxExpenseVatTreatment" AS ENUM ('PENDING_REVIEW','CREDITABLE','NON_CREDITABLE','OUT_OF_SCOPE');
CREATE TYPE "TaxExpenseCitTreatment" AS ENUM ('PENDING_REVIEW','DEDUCTIBLE','NON_DEDUCTIBLE','PARTIALLY_DEDUCTIBLE');
CREATE TYPE "TaxExpenseWhtTreatment" AS ENUM ('NOT_APPLICABLE','PENDING_REVIEW','WITHHOLDING_REQUIRED','WITHHELD');
CREATE TYPE "TaxExpenseEvidenceStatus" AS ENUM ('MISSING','PENDING_REVIEW','VERIFIED','REJECTED');
CREATE TYPE "TaxExpenseAssessmentStatus" AS ENUM ('DRAFT','FINALIZED','SUPERSEDED');
CREATE TYPE "TaxExpenseAttachmentType" AS ENUM ('TAX_INVOICE','RECEIPT','WITHHOLDING_CERTIFICATE','SUPPORTING_DOCUMENT','OTHER');
CREATE TYPE "TaxExpenseLifecycleEventType" AS ENUM ('CREATED','RECORDED','REVIEW_REQUESTED','ASSESSMENT_FINALIZED','VOIDED');

CREATE TABLE "TaxExpenseCategory" ("id" SERIAL NOT NULL,"branchId" INTEGER NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "TaxExpenseCategory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaxExpense" ("id" SERIAL NOT NULL,"branchId" INTEGER NOT NULL,"supplierId" INTEGER,"expenseNumber" TEXT NOT NULL,"counterpartyType" "TaxExpenseCounterpartyType" NOT NULL,"counterpartyName" TEXT NOT NULL,"counterpartyTaxId" TEXT,"documentNumber" TEXT,"documentDate" TIMESTAMP(3),"expenseDate" TIMESTAMP(3) NOT NULL,"receivedAt" TIMESTAMP(3),"status" "TaxExpenseStatus" NOT NULL DEFAULT 'DRAFT',"evidenceStatus" "TaxExpenseEvidenceStatus" NOT NULL DEFAULT 'MISSING',"currency" VARCHAR(3) NOT NULL DEFAULT 'THB',"subtotalAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"vatAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"totalAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"withholdingTaxAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"paymentDueAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"note" TEXT,"createdByEmployeeId" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "TaxExpense_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaxExpenseItem" ("id" SERIAL NOT NULL,"taxExpenseId" INTEGER NOT NULL,"categoryId" INTEGER NOT NULL,"lineNumber" INTEGER NOT NULL,"description" TEXT NOT NULL,"quantity" DECIMAL(14,2) NOT NULL DEFAULT 1,"unitAmount" DECIMAL(14,2) NOT NULL,"subtotalAmount" DECIMAL(14,2) NOT NULL,"vatTreatment" "TaxExpenseVatTreatment" NOT NULL DEFAULT 'PENDING_REVIEW',"vatAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"citTreatment" "TaxExpenseCitTreatment" NOT NULL DEFAULT 'PENDING_REVIEW',"whtTreatment" "TaxExpenseWhtTreatment" NOT NULL DEFAULT 'NOT_APPLICABLE',"withholdingTaxRate" DECIMAL(5,2),"withholdingTaxAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TaxExpenseItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaxExpenseAssessment" ("id" SERIAL NOT NULL,"taxExpenseId" INTEGER NOT NULL,"version" INTEGER NOT NULL,"status" "TaxExpenseAssessmentStatus" NOT NULL DEFAULT 'DRAFT',"vatTreatment" "TaxExpenseVatTreatment" NOT NULL,"citTreatment" "TaxExpenseCitTreatment" NOT NULL,"whtTreatment" "TaxExpenseWhtTreatment" NOT NULL,"assessmentNote" TEXT,"assessmentSnapshot" JSONB,"assessmentHash" TEXT NOT NULL,"assessedByEmployeeId" INTEGER,"assessedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TaxExpenseAssessment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaxExpenseLifecycleEvent" ("id" SERIAL NOT NULL,"taxExpenseId" INTEGER NOT NULL,"eventType" "TaxExpenseLifecycleEventType" NOT NULL,"previousStatus" "TaxExpenseStatus","resultingStatus" "TaxExpenseStatus","actorEmployeeId" INTEGER,"reasonCode" TEXT,"note" TEXT,"metadata" JSONB,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TaxExpenseLifecycleEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaxExpenseAttachment" ("id" SERIAL NOT NULL,"taxExpenseId" INTEGER NOT NULL,"attachmentType" "TaxExpenseAttachmentType" NOT NULL,"evidenceStatus" "TaxExpenseEvidenceStatus" NOT NULL DEFAULT 'PENDING_REVIEW',"storageKey" TEXT NOT NULL,"originalFileName" TEXT NOT NULL,"contentType" TEXT NOT NULL,"byteSize" INTEGER NOT NULL,"sha256" TEXT NOT NULL,"uploadedByEmployeeId" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TaxExpenseAttachment_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "TaxExpenseCategory_branchId_code_key" ON "TaxExpenseCategory"("branchId","code"); CREATE INDEX "TaxExpenseCategory_branchId_active_idx" ON "TaxExpenseCategory"("branchId","active");
CREATE UNIQUE INDEX "TaxExpense_branchId_expenseNumber_key" ON "TaxExpense"("branchId","expenseNumber"); CREATE INDEX "TaxExpense_branchId_status_expenseDate_idx" ON "TaxExpense"("branchId","status","expenseDate"); CREATE INDEX "TaxExpense_branchId_supplierId_idx" ON "TaxExpense"("branchId","supplierId"); CREATE INDEX "TaxExpense_branchId_documentNumber_idx" ON "TaxExpense"("branchId","documentNumber"); CREATE INDEX "TaxExpense_createdByEmployeeId_idx" ON "TaxExpense"("createdByEmployeeId");
CREATE UNIQUE INDEX "TaxExpenseItem_taxExpenseId_lineNumber_key" ON "TaxExpenseItem"("taxExpenseId","lineNumber"); CREATE INDEX "TaxExpenseItem_categoryId_idx" ON "TaxExpenseItem"("categoryId");
CREATE UNIQUE INDEX "TaxExpenseAssessment_taxExpenseId_version_key" ON "TaxExpenseAssessment"("taxExpenseId","version"); CREATE UNIQUE INDEX "TaxExpenseAssessment_taxExpenseId_assessmentHash_key" ON "TaxExpenseAssessment"("taxExpenseId","assessmentHash"); CREATE INDEX "TaxExpenseAssessment_assessedByEmployeeId_idx" ON "TaxExpenseAssessment"("assessedByEmployeeId");
CREATE INDEX "TaxExpenseLifecycleEvent_taxExpenseId_occurredAt_idx" ON "TaxExpenseLifecycleEvent"("taxExpenseId","occurredAt"); CREATE INDEX "TaxExpenseLifecycleEvent_actorEmployeeId_idx" ON "TaxExpenseLifecycleEvent"("actorEmployeeId"); CREATE INDEX "TaxExpenseLifecycleEvent_eventType_occurredAt_idx" ON "TaxExpenseLifecycleEvent"("eventType","occurredAt"); CREATE UNIQUE INDEX "TaxExpenseAttachment_taxExpenseId_sha256_key" ON "TaxExpenseAttachment"("taxExpenseId","sha256"); CREATE INDEX "TaxExpenseAttachment_uploadedByEmployeeId_idx" ON "TaxExpenseAttachment"("uploadedByEmployeeId");

ALTER TABLE "TaxExpenseCategory" ADD CONSTRAINT "TaxExpenseCategory_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpense" ADD CONSTRAINT "TaxExpense_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpense" ADD CONSTRAINT "TaxExpense_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpense" ADD CONSTRAINT "TaxExpense_createdByEmployeeId_fkey" FOREIGN KEY ("createdByEmployeeId") REFERENCES "EmployeeProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseItem" ADD CONSTRAINT "TaxExpenseItem_taxExpenseId_fkey" FOREIGN KEY ("taxExpenseId") REFERENCES "TaxExpense"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseItem" ADD CONSTRAINT "TaxExpenseItem_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "TaxExpenseCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseAssessment" ADD CONSTRAINT "TaxExpenseAssessment_taxExpenseId_fkey" FOREIGN KEY ("taxExpenseId") REFERENCES "TaxExpense"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseAssessment" ADD CONSTRAINT "TaxExpenseAssessment_assessedByEmployeeId_fkey" FOREIGN KEY ("assessedByEmployeeId") REFERENCES "EmployeeProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseLifecycleEvent" ADD CONSTRAINT "TaxExpenseLifecycleEvent_taxExpenseId_fkey" FOREIGN KEY ("taxExpenseId") REFERENCES "TaxExpense"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseLifecycleEvent" ADD CONSTRAINT "TaxExpenseLifecycleEvent_actorEmployeeId_fkey" FOREIGN KEY ("actorEmployeeId") REFERENCES "EmployeeProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseAttachment" ADD CONSTRAINT "TaxExpenseAttachment_taxExpenseId_fkey" FOREIGN KEY ("taxExpenseId") REFERENCES "TaxExpense"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaxExpenseAttachment" ADD CONSTRAINT "TaxExpenseAttachment_uploadedByEmployeeId_fkey" FOREIGN KEY ("uploadedByEmployeeId") REFERENCES "EmployeeProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;