const express = require('express')
const router = express.Router()

const productCatalogController = require('../src/modules/product/catalog/controllers/productCatalogController')
const productCreateLegacyCompatibilityController = require('../src/modules/product/create/controllers/productCreateLegacyCompatibilityController')
const productCreateDropdownCompatibilityController = require('../src/modules/product/create/controllers/productCreateDropdownCompatibilityController')
const operationalProductRuntimeController = require('../src/modules/product/runtime/controllers/operationalProductRuntimeController')
const readyToSellController = require('../src/modules/product/readyToSell/controllers/readyToSellController')
const productDuplicatePreviewRoutes = require('../src/modules/product/duplicatePreview/routes/productDuplicatePreviewRoutes')
const productMaintenanceController = require('../src/modules/product/maintenance/controllers/productMaintenanceController')
const productPricingController = require('../src/modules/product/pricing/controllers/productPricingController')
const productMediaController = require('../src/modules/product/media/controllers/productMediaController')
const productLifecycleController = require('../src/modules/product/lifecycle/controllers/productLifecycleController')
const productStockModeMigrationController = require('../src/modules/product/stockModeMigration/controllers/productStockModeMigrationController')
const verifyToken = require('../middlewares/verifyToken')

router.get('/online/dropdowns', productCreateDropdownCompatibilityController.getProductDropdowns)
router.get('/online/search', operationalProductRuntimeController.getProductsForOnline)
router.get('/online/detail/:id', operationalProductRuntimeController.getProductOnlineById)

router.use(verifyToken)

router.get('/dropdowns', productCreateDropdownCompatibilityController.getProductDropdowns)
router.use('/duplicate-preview', productDuplicatePreviewRoutes)
router.get('/pos/search', operationalProductRuntimeController.getProductsForPos)
router.get('/pos/runtime-by-template/:templateProductId', operationalProductRuntimeController.getOperationalProductByTemplateId)
router.post('/pos/create-local', operationalProductRuntimeController.createLocalOperationalProduct)
router.post('/pos/create-from-template', operationalProductRuntimeController.createOperationalProductFromTemplate)
router.get('/pos/:id', operationalProductRuntimeController.getProductPosById)

router.get('/ready-to-sell', readyToSellController.getReadyToSellProducts)
router.get('/ready-to-sell/structured/:productId', readyToSellController.getStructuredReadyToSellDetails)

router.get('/', productCatalogController.getAllProducts)
router.post('/', productCreateLegacyCompatibilityController.createProduct)
router.patch('/:id', productMaintenanceController.updateProduct)
router.post('/:id/disable', productLifecycleController.disableProduct)
router.post('/:id/enable', productLifecycleController.enableProduct)
router.get('/:id/delete-check', productLifecycleController.getProductDeleteCheck)
router.patch('/:id/archive', productLifecycleController.archiveProduct)
router.get('/:id', operationalProductRuntimeController.getProductPosById)
router['delete']('/:id', productLifecycleController.deleteProduct)
router['delete']('/:id/images', productMediaController.deleteProductImage)
router.post('/:id/migrate-to-simple', productStockModeMigrationController.migrateSnToSimple)

router.get('/:productId/prices', productPricingController.getProductPrices)
router.put('/:productId/prices', productPricingController.updateProductPrices)
router.post('/:productId/prices', productPricingController.addProductPrice)
router['delete']('/:productId/prices/:priceId', productPricingController.deleteProductPrice)

module.exports = router
