const express = require('express');
const verifyToken = require('../../../../middlewares/verifyToken');
const { completeSaleController } = require('../completion/controllers/saleCompletionController');
const { createSale } = require('../create/controllers/saleLegacyCreateController');
const { updateSaleDocumentLinesController } = require('../documents/controllers/saleDocumentController');
const { getSaleDeliveryNote, issueSaleDeliveryNoteController } = require('../documents/controllers/saleDeliveryNoteController');
const { getAllSales, getAllSalesReturn, getSaleById, searchPrintableSales } = require('../history/controllers/saleHistoryController');
const { searchSaleItemsController } = require('../item-search/controllers/saleItemSearchController');
const { getSaleQuotationReferenceController } = require('../lineage/saleQuotationReferenceController');
const { markSaleAsPaid } = require('../settlement/controllers/saleSettlementController');
const saleReturnRoutes = require('../return/routes/saleReturnRoutes');
const posHeldCartRoutes = require('../held-cart/routes/posHeldCartRoutes');
const quotationRoutes = require('../../quotation/http/quotationRoutes');

const router = express.Router();
router.use(verifyToken);
router.use('/quotations', quotationRoutes);
router.use('/held-carts', posHeldCartRoutes);
router.get('/items/search', searchSaleItemsController);
router.post('/complete', completeSaleController);
router.use('/returns', saleReturnRoutes);
router.post('/', createSale);
router.get('/', getAllSales);
router.get('/return', getAllSalesReturn);
router.get('/printable', searchPrintableSales);
router.get('/printable-sales', searchPrintableSales);
router.put('/:id/document-lines', updateSaleDocumentLinesController);
router.post('/:id/delivery-note', issueSaleDeliveryNoteController);
router.get('/:id/delivery-note', getSaleDeliveryNote);
router.get('/:id/quotation-reference', getSaleQuotationReferenceController);
router.put('/:id/document-descriptions', updateSaleDocumentLinesController);
router.get('/:id', getSaleById);
router.post('/:id/mark-paid', markSaleAsPaid);

module.exports = router;
