'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const sql = fs.readFileSync(path.join(__dirname, 'migration.sql'), 'utf8');
assert.match(sql, /ADD COLUMN "departmentName" TEXT/);
assert.match(sql, /ADD COLUMN "financialOwnerCustomerId" INTEGER/);
assert.match(sql, /CustomerProfile_branchId_financialOwnerCustomerId_idx/);
assert.match(sql, /FOREIGN KEY \("financialOwnerCustomerId"\)/);
assert.match(sql, /ON DELETE RESTRICT/);
assert.doesNotMatch(sql, /DROP|TRUNCATE|DELETE FROM/i);
console.log('customer-financial-group migration: PASS');
