const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, 'quickReceiptSessionController.js'), 'utf8')

assert.match(source, /requireActor\(req, res\)/)
assert.match(source, /service\.createDraft\(req\.body \|\| \{\}, actor\.branchId, actor\.employeeId\)/)
assert.match(source, /completeService\.complete\(/[\s\S]*req\.get\('X-Idempotency-Key'\)/)
assert.match(source, /service\.finalize\(req\.params\.id, actor\.branchId, actor\.employeeId, req\.get\('X-Idempotency-Key'\)\)/)
assert.match(source, /Number\(data\?\.id\) !== Number\(req\.params\.id\)/)
assert.match(source, /IDEMPOTENCY_KEY_CONFLICT/)
assert.match(source, /service\.cancel\(req\.params\.id, actor\.branchId, req\.body\?\.reason\)/)
assert.match(source, /normalizeError\(rawError\)/)
assert.match(source, /databaseCode === '23505'/)
assert.match(source, /INVENTORY_IDENTITY_ALREADY_EXISTS/)
assert.match(source, /Barcode หรือ Serial Number นี้มีอยู่ในระบบแล้ว/)
assert.match(source, /details: error\?\.details/)

console.log('✅ quickReceiptSessionController HTTP contract passed')
