'use strict'
const express = require('express')
const verifyToken = require('../../../../middlewares/verifyToken')
const controller = require('../controllers/storeDeviceDurableJobController')
const registryController = require('../controllers/storeDeviceRegistryController')
const { createDeliveryNotePrintJob } = require('../print/createDeliveryNotePrintJobController')
const { createOutputTaxInvoicePrintJob } = require('../print/createOutputTaxInvoicePrintJobController')
const { createSaleReceiptPrintJob } = require('../print/createSaleReceiptPrintJobController')
const { leasePrintDocumentJob } = require('../print/leasePrintDocumentJobController')
const router = express.Router()
router.use(verifyToken)
router.post('/gateways', controller.registerGateway)
router.post('/gateways/:gatewayId/sessions', controller.authenticateSession)
router.post('/gateways/:gatewayId/sessions/:sessionId/reconnect', controller.reconnectSession)
router.post('/gateways/:gatewayId/sessions/:sessionId/heartbeat', controller.heartbeat)
router.post('/gateways/:gatewayId/sessions/:sessionId/disconnect', controller.disconnectSession)
router.post('/gateways/:gatewayId/rotate', controller.rotateGateway)
router.post('/gateways/:gatewayId/revoke', controller.revokeGateway)
router.post('/devices', registryController.register)
router.get('/devices', registryController.list)
router.get('/devices/:deviceId', registryController.detail)
router.post('/devices/:deviceId/rename', registryController.rename)
router.post('/devices/:deviceId/workstation', registryController.assignWorkstation)
router.post('/devices/:deviceId/revoke', registryController.revoke)
router.post('/print/delivery-notes/:saleId/jobs', createDeliveryNotePrintJob)
router.post('/print/output-tax-invoices/:taxDocumentId/jobs', createOutputTaxInvoicePrintJob)
router.post('/print/sale-receipts/:paymentId/jobs', createSaleReceiptPrintJob)
router.post('/print/jobs/:jobId/leases', leasePrintDocumentJob)
router.post('/jobs', controller.createJob)
router.get('/jobs', controller.listJobs)
router.get('/jobs/:jobId', controller.getJob)
router.post('/jobs/:jobId/leases', controller.leaseJob)
router.post('/leases/:leaseId/acknowledge', controller.acknowledge)
router.post('/leases/:leaseId/progress', controller.progress)
router.post('/leases/:leaseId/complete', controller.complete)
router.post('/leases/:leaseId/fail', controller.fail)
router.post('/jobs/:jobId/retry', controller.retry)
router.get('/diagnostics', controller.diagnostics)
module.exports = router
