'use strict'
const express = require('express')
const verifyToken = require('../../../../middlewares/verifyToken')
const controller = require('../controllers/storeDeviceDurableJobController')
const router = express.Router()
router.use(verifyToken)
router.post('/gateways', controller.registerGateway)
router.post('/gateways/:gatewayId/sessions', controller.authenticateSession)
router.post('/gateways/:gatewayId/sessions/:sessionId/reconnect', controller.reconnectSession)
router.post('/gateways/:gatewayId/sessions/:sessionId/heartbeat', controller.heartbeat)
router.post('/gateways/:gatewayId/sessions/:sessionId/disconnect', controller.disconnectSession)
router.post('/gateways/:gatewayId/rotate', controller.rotateGateway)
router.post('/gateways/:gatewayId/revoke', controller.revokeGateway)
router.post('/jobs', controller.createJob)
router.get('/jobs', controller.listJobs)
router.get('/jobs/:jobId', controller.getJob)
router.post('/jobs/:jobId/leases', controller.leaseJob)
router.post('/leases/:leaseId/acknowledge', controller.acknowledge)
router.post('/leases/:leaseId/progress', controller.progress)
router.post('/leases/:leaseId/complete', controller.complete)
router.post('/leases/:leaseId/fail', controller.fail)
router.post('/jobs/:jobId/retry', controller.retry)
router.get('/diagnostics', controller.diagnostics)
module.exports = router
