const POSITION_CAPABILITIES = Object.freeze({
  EMPLOYEE_MANAGE: 'employee.manage',
  REPAIR_READ: 'repair.read',
  REPAIR_INTAKE: 'repair.intake',
  REPAIR_WORKFLOW: 'repair.workflow',
  REPAIR_PARTS: 'repair.parts',
  REPAIR_ESTIMATE: 'repair.estimate',
  REPAIR_CLAIM: 'repair.claim',
  REPAIR_HANDOVER: 'repair.handover',
  REPAIR_CUSTOMER_ACCESS: 'repair.customer-access',
  REPAIR_CUSTOMER_OVERRIDE: 'repair.customer-override',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  INVENTORY_AUDIT: 'inventory.audit',
  INVENTORY_AUDIT_FINALIZE: 'inventory.audit.finalize',
  INVENTORY_RECEIVE: 'inventory.receive',
  INVENTORY_LIFECYCLE: 'inventory.lifecycle',
  INVENTORY_QUICK_STOCK: 'inventory.quick-stock',
  INVENTORY_QUICK_RECEIPT: 'inventory.quick-receipt',
  INVENTORY_QUICK_RECEIPT_FINALIZE: 'inventory.quick-receipt.finalize',
  PROCUREMENT_RECEIPT: 'procurement.receipt',
  PROCUREMENT_RECEIPT_FINALIZE: 'procurement.receipt.finalize',
  PROCUREMENT_PURCHASE_ORDER: 'procurement.purchase-order',
  PROCUREMENT_PURCHASE_ORDER_CONTROL: 'procurement.purchase-order.control',
  PROCUREMENT_SUPPLIER: 'procurement.supplier',
  PROCUREMENT_SUPPLIER_DELETE: 'procurement.supplier.delete',
  PROCUREMENT_SUPPLIER_PAYMENT_READ: 'procurement.supplier-payment.read',
  PROCUREMENT_SUPPLIER_PAYMENT_MANAGE: 'procurement.supplier-payment.manage',
  PROCUREMENT_SUPPLIER_PAYMENT_VOID: 'procurement.supplier-payment.void',
  SALES_CORE: 'sales.core',
  SALES_COMPLETE: 'sales.complete',
  SALES_RETURN: 'sales.return',
  SALES_RETURN_DEDUCTION_APPROVE: 'sales.return.deduction-approve',
  SALES_PAYMENT_READ: 'sales.payment.read',
  SALES_PAYMENT_MANAGE: 'sales.payment.manage',
  SALES_PAYMENT_CANCEL: 'sales.payment.cancel',
  SALES_SETTLEMENT_CLOSE: 'sales.settlement.close',
  SALES_DOCUMENT_PREPARE: 'sales.document.prepare',
  SALES_DOCUMENT_LOCK: 'sales.document.lock',
  SALES_DOCUMENT_REPLACE: 'sales.document.replace',
  SALES_DOCUMENT_TAX_PUBLISH: 'sales.document.tax-publish',
  TAX_OUTPUT_READ: 'tax.output.read',
  TAX_OUTPUT_PREPARE: 'tax.output.prepare',
  TAX_OUTPUT_ISSUE: 'tax.output.issue',
  TAX_OUTPUT_CREDIT_NOTE: 'tax.output.credit-note',
  TAX_OUTPUT_LIFECYCLE: 'tax.output.lifecycle',
  TAX_OUTPUT_FILING_READ: 'tax.output.filing.read',
  TAX_OUTPUT_FILING_PREPARE: 'tax.output.filing.prepare',
  TAX_OUTPUT_FILING_SUBMIT: 'tax.output.filing.submit',
  TAX_INPUT_READ: 'tax.input.read',
  TAX_INPUT_REVIEW: 'tax.input.review',
  TAX_INPUT_FILING: 'tax.input.filing',
  TAX_INPUT_AUDIT: 'tax.input.audit',
  TAX_INPUT_PERIOD_CONTROL: 'tax.input.period-control',
  TAX_PERIOD_READ: 'tax.period.read',
  TAX_PERIOD_MANAGE: 'tax.period.manage',
  TAX_PERIOD_REOPEN: 'tax.period.reopen',
  TAX_CLOSING_HANDOFF_READ: 'tax.closing-handoff.read',
  TAX_CLOSING_HANDOFF_FINALIZE: 'tax.closing-handoff.finalize',
});

const REPAIR_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.REPAIR_READ,
  POSITION_CAPABILITIES.REPAIR_INTAKE,
  POSITION_CAPABILITIES.REPAIR_WORKFLOW,
  POSITION_CAPABILITIES.REPAIR_PARTS,
  POSITION_CAPABILITIES.REPAIR_ESTIMATE,
  POSITION_CAPABILITIES.REPAIR_CLAIM,
  POSITION_CAPABILITIES.REPAIR_HANDOVER,
  POSITION_CAPABILITIES.REPAIR_CUSTOMER_ACCESS,
  POSITION_CAPABILITIES.REPAIR_CUSTOMER_OVERRIDE,
]);

const INVENTORY_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.INVENTORY_ADJUST,
  POSITION_CAPABILITIES.INVENTORY_TRANSFER,
  POSITION_CAPABILITIES.INVENTORY_AUDIT,
  POSITION_CAPABILITIES.INVENTORY_AUDIT_FINALIZE,
  POSITION_CAPABILITIES.INVENTORY_RECEIVE,
  POSITION_CAPABILITIES.INVENTORY_LIFECYCLE,
  POSITION_CAPABILITIES.INVENTORY_QUICK_STOCK,
  POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT,
  POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT_FINALIZE,
]);

const PROCUREMENT_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.PROCUREMENT_RECEIPT,
  POSITION_CAPABILITIES.PROCUREMENT_RECEIPT_FINALIZE,
  POSITION_CAPABILITIES.PROCUREMENT_PURCHASE_ORDER,
  POSITION_CAPABILITIES.PROCUREMENT_PURCHASE_ORDER_CONTROL,
  POSITION_CAPABILITIES.PROCUREMENT_SUPPLIER,
  POSITION_CAPABILITIES.PROCUREMENT_SUPPLIER_DELETE,
  POSITION_CAPABILITIES.PROCUREMENT_SUPPLIER_PAYMENT_READ,
]);

const SALES_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.SALES_CORE,
  POSITION_CAPABILITIES.SALES_COMPLETE,
  POSITION_CAPABILITIES.SALES_RETURN,
  POSITION_CAPABILITIES.SALES_PAYMENT_READ,
  POSITION_CAPABILITIES.SALES_PAYMENT_MANAGE,
  POSITION_CAPABILITIES.SALES_PAYMENT_CANCEL,
  POSITION_CAPABILITIES.SALES_SETTLEMENT_CLOSE,
  POSITION_CAPABILITIES.SALES_DOCUMENT_PREPARE,
  POSITION_CAPABILITIES.SALES_DOCUMENT_LOCK,
  POSITION_CAPABILITIES.SALES_DOCUMENT_REPLACE,
  POSITION_CAPABILITIES.SALES_DOCUMENT_TAX_PUBLISH,
]);

const OUTPUT_TAX_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.TAX_OUTPUT_READ,
  POSITION_CAPABILITIES.TAX_OUTPUT_PREPARE,
  POSITION_CAPABILITIES.TAX_OUTPUT_ISSUE,
  POSITION_CAPABILITIES.TAX_OUTPUT_CREDIT_NOTE,
  POSITION_CAPABILITIES.TAX_OUTPUT_LIFECYCLE,
]);

const OUTPUT_TAX_FILING_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.TAX_OUTPUT_FILING_READ,
  POSITION_CAPABILITIES.TAX_OUTPUT_FILING_PREPARE,
  POSITION_CAPABILITIES.TAX_OUTPUT_FILING_SUBMIT,
]);

const INPUT_TAX_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.TAX_INPUT_READ,
  POSITION_CAPABILITIES.TAX_INPUT_REVIEW,
  POSITION_CAPABILITIES.TAX_INPUT_FILING,
  POSITION_CAPABILITIES.TAX_INPUT_AUDIT,
  POSITION_CAPABILITIES.TAX_INPUT_PERIOD_CONTROL,
]);

const TAX_PERIOD_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.TAX_PERIOD_READ,
  POSITION_CAPABILITIES.TAX_PERIOD_MANAGE,
  POSITION_CAPABILITIES.TAX_PERIOD_REOPEN,
]);

const TAX_CLOSING_HANDOFF_CAPABILITIES = Object.freeze([
  POSITION_CAPABILITIES.TAX_CLOSING_HANDOFF_READ,
  POSITION_CAPABILITIES.TAX_CLOSING_HANDOFF_FINALIZE,
]);

const normalizeUpper = (value) => String(value || '').trim().toUpperCase();

const normalizeCapabilityArray = (value) => {
  if (!Array.isArray(value)) return null;
  return [...new Set(value
    .map((item) => String(item || '').trim())
    .filter(Boolean))];
};

const legacyCapabilitiesForRole = (role) => {
  const normalized = normalizeUpper(role);

  if (normalized === 'OWNER' || normalized === 'MANAGER') {
    return [
      POSITION_CAPABILITIES.EMPLOYEE_MANAGE,
      ...REPAIR_CAPABILITIES,
      ...INVENTORY_CAPABILITIES,
      ...PROCUREMENT_CAPABILITIES,
      ...SALES_CAPABILITIES,
      ...OUTPUT_TAX_CAPABILITIES,
      ...OUTPUT_TAX_FILING_CAPABILITIES,
      ...INPUT_TAX_CAPABILITIES,
      ...TAX_PERIOD_CAPABILITIES,
      ...TAX_CLOSING_HANDOFF_CAPABILITIES,
      POSITION_CAPABILITIES.SALES_RETURN_DEDUCTION_APPROVE,
      POSITION_CAPABILITIES.PROCUREMENT_SUPPLIER_PAYMENT_MANAGE,
      ...(normalized === 'OWNER'
        ? [POSITION_CAPABILITIES.PROCUREMENT_SUPPLIER_PAYMENT_VOID]
        : []),
    ];
  }

  if (normalized === 'CASHIER') {
    return [
      POSITION_CAPABILITIES.REPAIR_READ,
      POSITION_CAPABILITIES.REPAIR_INTAKE,
      POSITION_CAPABILITIES.REPAIR_ESTIMATE,
      POSITION_CAPABILITIES.REPAIR_CLAIM,
      POSITION_CAPABILITIES.REPAIR_CUSTOMER_ACCESS,
      POSITION_CAPABILITIES.INVENTORY_AUDIT,
      POSITION_CAPABILITIES.INVENTORY_AUDIT_FINALIZE,
      POSITION_CAPABILITIES.INVENTORY_RECEIVE,
      POSITION_CAPABILITIES.INVENTORY_LIFECYCLE,
      POSITION_CAPABILITIES.INVENTORY_QUICK_STOCK,
      POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT,
      POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT_FINALIZE,
      ...PROCUREMENT_CAPABILITIES,
      ...SALES_CAPABILITIES,
      ...OUTPUT_TAX_FILING_CAPABILITIES,
    ];
  }

  if (normalized === 'TECHNICIAN') {
    return [
      POSITION_CAPABILITIES.REPAIR_READ,
      POSITION_CAPABILITIES.REPAIR_WORKFLOW,
      POSITION_CAPABILITIES.REPAIR_PARTS,
      POSITION_CAPABILITIES.INVENTORY_AUDIT,
      POSITION_CAPABILITIES.INVENTORY_AUDIT_FINALIZE,
      POSITION_CAPABILITIES.INVENTORY_RECEIVE,
      POSITION_CAPABILITIES.INVENTORY_LIFECYCLE,
      POSITION_CAPABILITIES.INVENTORY_QUICK_STOCK,
      POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT,
      POSITION_CAPABILITIES.INVENTORY_QUICK_RECEIPT_FINALIZE,
      ...PROCUREMENT_CAPABILITIES,
      ...SALES_CAPABILITIES,
      ...OUTPUT_TAX_FILING_CAPABILITIES,
    ];
  }

  return [];
};

const deriveCompatibilityRoleFromPosition = (position = {}) => {
  const capabilities = normalizeCapabilityArray(position.capabilities);
  if (capabilities === null) return null;
  return capabilities.includes(POSITION_CAPABILITIES.EMPLOYEE_MANAGE)
    ? 'MANAGER'
    : 'CASHIER';
};

const resolveActorCapabilities = (actor = {}) => {
  const systemRole = normalizeUpper(actor.role);
  if (actor.isSuperAdmin || systemRole === 'SUPERADMIN' || systemRole === 'ADMIN') {
    return {
      mode: 'SYSTEM_ROLE',
      capabilities: Object.values(POSITION_CAPABILITIES),
    };
  }

  const positionCapabilities = normalizeCapabilityArray(actor.positionCapabilities);
  if (positionCapabilities !== null) {
    return {
      mode: 'POSITION',
      capabilities: positionCapabilities,
    };
  }

  return {
    mode: 'V2_ROLE_COMPAT',
    capabilities: legacyCapabilitiesForRole(actor.employeeRole || actor.v2Role),
  };
};

const hasCapability = (actor, capability) => {
  const key = String(capability || '').trim();
  if (!key) return false;
  return resolveActorCapabilities(actor).capabilities.includes(key);
};

module.exports = {
  POSITION_CAPABILITIES,
  REPAIR_CAPABILITIES,
  INVENTORY_CAPABILITIES,
  PROCUREMENT_CAPABILITIES,
  SALES_CAPABILITIES,
  OUTPUT_TAX_CAPABILITIES,
  OUTPUT_TAX_FILING_CAPABILITIES,
  INPUT_TAX_CAPABILITIES,
  TAX_PERIOD_CAPABILITIES,
  TAX_CLOSING_HANDOFF_CAPABILITIES,
  normalizeCapabilityArray,
  legacyCapabilitiesForRole,
  deriveCompatibilityRoleFromPosition,
  resolveActorCapabilities,
  hasCapability,
};
